spring:
  application:
    name: spring-cloud-provider
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=JST
    username: root
    password: Lhg097095
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
#    password: 
#    jedis:
#      pool:
#        max-idle: 200
#        max-wait: 10000
#        max-active: 1024
#    timeout: 10000
    
    
   
server:
  port: 10080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
#    fetch-registry: false
#    register-with-eureka: false
